/**
 * Icon map generator (`pnpm icons:generate`), ADR 0034.
 *
 * Reads the pinned `iconoir` package's 24×24 regular SVGs and writes two committed files
 * under `src/core/ui/icons/`:
 *  - `names.ts`: the icon name list + `IconName` type. Has no SVG data, so validation can
 *    use it on the client as well.
 *  - `svg.ts`: name → inner SVG markup, `server-only`. `<Icon>` inlines it into the static HTML.
 *
 * The outer `<svg>` is dropped (`<Icon>` renders its own). Children's `stroke-width` of
 * ~1.5 is dropped too, so `<Icon strokeWidth>` (set on the root) applies to the whole
 * icon. Re-run after bumping `iconoir`. The output is deterministic (sorted by name).
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const SRC_DIR = path.resolve(process.cwd(), "node_modules/iconoir/icons/regular");
const OUT_DIR = path.resolve(process.cwd(), "src/core/ui/icons");
const version = (JSON.parse(readFileSync(path.resolve(process.cwd(), "node_modules/iconoir/package.json"), "utf8")) as { version: string }).version;

const header = `// GENERATED by scripts/generate-icons.ts from iconoir@${version}. Do not edit.\n`;

const icons = readdirSync(SRC_DIR)
  .filter((f) => f.endsWith(".svg"))
  .map((f) => f.slice(0, -4))
  .sort()
  .map((name) => {
    const raw = readFileSync(path.join(SRC_DIR, `${name}.svg`), "utf8").trim();
    const open = raw.indexOf(">");
    const close = raw.lastIndexOf("</svg>");
    if (!raw.startsWith("<svg") || open < 0 || close < 0) throw new Error(`Unexpected SVG shape: ${name}`);
    const inner = raw
      .slice(open + 1, close)
      .replace(/ stroke-width="1\.(49\d*|5|50\d*)"/g, "")
      .replace(/\s*\n\s*/g, "")
      .trim();
    return { name, inner };
  });

writeFileSync(
  path.join(OUT_DIR, "names.ts"),
  `${header}
/** Every icon name \`<Icon>\` can render (iconoir regular set). */
export const ICON_NAMES = ${JSON.stringify(icons.map((i) => i.name), null, 2)} as const;

export type IconName = (typeof ICON_NAMES)[number];

const NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES);

/** True if \`name\` is a renderable icon (validation + fallback guard). */
export function isIconName(name: string): name is IconName {
  return NAME_SET.has(name);
}
`,
);

writeFileSync(
  path.join(OUT_DIR, "svg.ts"),
  `${header}import "server-only";
import type { IconName } from "./names";

/** Icon name → inner SVG markup (24×24 viewBox, \`stroke="currentColor"\`). */
export const ICON_SVG: Record<IconName, string> = {
${icons.map((i) => `  ${JSON.stringify(i.name)}: ${JSON.stringify(i.inner)},`).join("\n")}
};
`,
);

console.log(`Wrote ${icons.length} icons from iconoir@${version} to ${path.relative(process.cwd(), OUT_DIR)}/`);
